<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Emporio\Model\Franquicias;

class FranquiciasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array
    	(
    		/*[
    			'franquicia' => '',
    			'resumen' => '',
    			'logo' => '',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '',
    			'retorno_inversion' => '',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],*/

    		[
    			'franquicia' => 'PUNTO AGUACATE',
    			'resumen' => 'PUNTO AGUACATE ES UN RESTAURANT DONDE NUESTRO INGREDIENTE PRINCIPAL ES EL AGUACATE. Deliciosos Sándwiches, Bagels y una barra con amplia variedad de ingredientes a elegir. Aderezos 100% artesanales que dan el toque especial.',
    			'logo' => 'punto_aguacate.jpg',
    			'nosotros' => 'Somos una empresa que se dedica a la preparación de Sándwich, Bagels y Ensaladas, en un modelo “Fast Food” y un servicio donde siempre el cliente ve como preparamos sus alimentos. Contamos con dos modelos de negocio: Food Court y Restaurant',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 120,000.00',
    			'adaptacion_local' => '$ 100,000.00',
    			'regalias' => '$5,000.00 MENSUALES',
    			'publicidad' => '2% SOBRE VENTAS BRUTAS',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
                'inversion' => '',
    			'retorno_inversion' => '12 A 18 MESES',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],
            
    		[
    			'franquicia' => 'VENTUSTO CAFÉ',
    			'resumen' => '',
    			'logo' => 'vetusto_cafe.jpg',
    			'nosotros' => '',
    			'historia' => 'VETUSTO CAFÉ® inicio como Liscio Caffe ubicado en la Av. Morelos y 29 No. 19, Fracc. San Antonio en la cuidad de Cuahtemoc,Chihuahua. En febrero de 2008 se tuesta café para garantizar frescura, calidad y abasto del mercado propio en una tostadora tradicional de bajo volumen. En febrero de 2018 se crea VETUSTO CAFÉ® CLUB enfocado a los amantes del café con catas, y técnicas de preparación.',
    			'mision' => 'Ofrecer a los clientes el mejor producto como jamas hayan encontrado. A través de una excelente calidad y servicio.',
    			'vision' => 'Ser una compañía a la cual los clientes elijan, los competidores respeten y los empleados disfruten.',
    			'cuota_inicial' => '$10,000.00 DOLARES MÁS IVA',
    			'adaptacion_local' => '',
    			'regalias' => '4% MENSUAL DE VENTAS LIBRES DE IMPUESTOS',
    			'publicidad' => '1% MENSUAL',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '$5,000.00 DOLARES (2 MESES)',
                'retorno_inversion' => '',
    			'inversion' => '',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],
            
    		[
    			'franquicia' => 'ESSENZIA ESPAÑOLA',
    			'resumen' => 'cuenta con un modelo de negocio que otorga una alta rentabilidad a sus franquiciatarios, ofreciendo una marca de prestigio, una red de distribución de alto nivel, productos provenientes de las principales fábricas de Asia y sobre todo brinda una asistencia técnica con calidad Premium. Todo esto para que sus franquiciatarios puedan brindar un servicio de excelencia a cada de una de sus clientas. Las boutiques ESSENZIA ESPAÑOLA® son el espacio donde las mujeres podrán plasmar sus ilusiones y sentimientos nupciales, encontrando el vestido de novia con el que siempre soñaron y realizando así su ajuar perfecto, todo esto para crear recuerdos inolvidables.',
    			'logo' => 'essenzia_espanola.jpg',
    			'nosotros' => '',
    			'historia' => 'En el año de 1972 surge la idea de nuestros fundadores de introducirse al mundo de la moda nupcial.Nuestros vestidos en ese tiempo se confeccionaban en pequeños talleres por modistas de gran corazón y con una amplia experiencia, debido al gran éxito surge “ESSENCE, UN SUEÑO DE NOVIA”, 40 años han pasado y muchos cambios se han generado desde ese entonces, pero el amor y la pasión por los vestidos de novia aún se conservan intactos, inclusive con fuerza mucho mayor. Después de cuatro décadas con orgullo decimos que han sido 40 años de sueños compartidos, de ilusiones cumplidas y de novias felices.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$400,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '0%',
    			'publicidad' => '$4,167.00 Mensual sobre ventas totales.',
    			'publicidad_institucional' => '2% Mensual sobre ventas totales.',
    			'capital_trabajo' => '',
                'inversion' => '',
    			'retorno_inversion' => '23 MESES',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '6 AÑOS',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '4',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'BRIST',
    			'resumen' => 'Brist es un modelo de negocios de nueva generación enfocada en los servicios. Todos nuestros servicios fueron diseñados como un proceso sistematizado, dicho conocimiento se encuentra redactado en manuales técnicos de procesos entregados en el momento de capacitación para cada sucursal. En ellos se describe paso a paso el proceso de los servicios ofrecido al usuario final por nuestra marca. En Brist “Apple Repair Service” nos especializamos en dar soporte a clientes con dispositivos de la marca Apple, atendiendo a sus necesidades de mantenimiento preventivo y correctivo, así como reciclaje.',
    			'logo' => 'brist.jpg',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$350,000.00',
    			'adaptacion_local' => '',
    			'regalias' => 'Asistencia técnica: $3,000.00, Publicidad: $2,000.00',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
                'inversion' => '',
    			'retorno_inversion' => '18 A 24 MESES',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '5 AÑOS',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '13',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'DA-CODEX',
    			'resumen' => 'Dos Barcas Capital, S.A. de C.V. (DBC) desarrolla y opera de centros de negocios.  Diseña, Construye, Fondea, Vende, Renta y Opera eficientemente oficinas privadas equipadas, accesibles y flexibles en su contratación.  Ofrecemos nuestro conocimiento integral para construir y operar Centro de Negocios que cuentan con diferentes espacios tales como: oficinas físicas privadas, espacios de coworking y oficinas virtuales y áreas comunes (salas de juntas, baños, etc.)',
    			'logo' => 'da_codex.gif',
    			'nosotros' => '',
    			'historia' => 'DBC se funda en 2014 y es albergada en el Parque de Innovación de la Universidad La Sallé de Chihuahua, AC (ULSA).  DBC crea y desarrolla su concepto para Rentar, Vender y Operar Oficinas en Centros de Negocios apoyada en el programa de incubación de la ULSA.  En 2015 inicia operaciones el primer Centro de Negocios de DBC que exitosa mente logra en 9 meses la máxima ocupación que mantiene a la fecha.  En 2016 implementamos nuestro programa de asesoramiento para el desarrollo de Centros de Negocios con experiencias en el estado de Sonora y de Chihuahua.  Hoy contamos con dos ubicaciones propias y una cartera permanente de cuatro proyectos en asesoría y/o asociación.  En 2018 evolucionamos nuestro programa de asesorías y creamos nuestro Modelo de Franquicia DACODEX.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$200,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '$2,500.00/mes POR USO DE MARCA',
    			'publicidad' => '$1,500.00 MENSUALES',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
                'inversion' => '',
    			'retorno_inversion' => '',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '5 AÑOS',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '13',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'LUCY´S SHAKE FACTORY',
    			'resumen' => 'Lucy’s Shake Factory es la primera barra de malteadas en México con un estilo vintage de los fabulosos y dulces años 50’s en donde nuestros clientes pueden crear su propia malteada a partir de la variedad de sabores y toppings que ofrecemos.',
    			'logo' => 'lucys_shake_factory.png',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => 'Creemos en el poder de la sonrisa. Creemos que el mundo es un lugar mejor cuando todos intercambiamos sonrisas. Es por eso que nos esforzamos por crear en nuestras sucursales un ambiente donde puedas crear momentos de felicidad con tus amigos y familia y las sonrisas que te lleves la contagies a más personas.',
    			'cuota_inicial' => '$220,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '4%',
    			'publicidad' => '',
    			'publicidad_institucional' => '2%',
    			'capital_trabajo' => '',
                'inversion' => '',
    			'retorno_inversion' => 'ENTRE 18 Y 24 MESES',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '5 AÑOS',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Giorger Pizza',
    			'resumen' => 'Giorger Pizza, es un modelo de Pizzeria restaurante express que actualmente tiene 38 años de experiencia en la elaboración, preparación y horneado de su deliciosa Pizza para consumo en comedor, así como para llevar. Giorger Pizza se preocupan por mantener un estricto control de calidad en la elaboración de la masa y la salsa, ambas son recetas de la casa y preparadas día a día. Su estilo y concepto se mantiene en un ambiente familiar y de buen gusto debido a sus especialidades y líneas de productos para aquellos gustos de los clientes tienen el “Have it your way” ( a tu manera) con la posibilidad de crear su propia pizza con su variedad de ingredientes. GIORGIOS PIZZA hoy, GIORGER PIZZA',
    			'logo' => 'giorger_pizza.png',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$180,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '4% Sobre ventas',
    			'publicidad' => '2%',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$900,000.00',
    			'retorno_inversion' => '18-24 meses',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'CLARO FISH JR.',
    			'resumen' => 'Claro Fish Jr.® es un restaurante de mariscos, especializado en tacos, tostadas, antojería y bebidas alcohólicas. Nuestra propuesta, se basa en la innovación y nuestro slogan “Gran Variedad de Mariscos Servidos sobre Tortilla”, ya que logramos revolucionar la manera de comer mariscos, con la creación de una gran variedad de recetas y presentación de nuestros platillos, bebidas y una atractiva barra de Salsas y Ensaladas.',
    			'logo' => 'claro_fish_jr.png',
    			'nosotros' => '',
    			'historia' => 'Claro Fisf Jr empezó con un pequeño puesto de tacos de pescado capeado llamado “Tacos Los Claros” ubicado en el Malecón de La Paz, después de casi 50 años de la llegada de Don Claro y su especial sazón, nace Claro Fish Jr.®, con sucursales en Cabo San Lucas, San José del Cabo y La Paz.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 350,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '5% SOBRE LAS VENTAS',
    			'publicidad' => '2%',
    			'publicidad_institucional' => '1%',
    			'capital_trabajo' => '',
    			'inversion' => 'Ciudad: $1,892,610.00, Playa: $1,890,790.00',
    			'retorno_inversion' => 'Ciudad 21 meses Playa 23 meses',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'NATURAL ADVENTURE FUN PARK',
    			'resumen' => 'Es un parque de aventura al aire libre, en el que ofrece espacios y juegos innovadores para que las familias se diviertan, realizando actividades físicas y retos en los que desarrollan sus habilidades motrices y superan sus fobias. Tipos de unidad: Urban, City y Metropoli',
    			'logo' => 'natural_adventure.jpg',
    			'nosotros' => '',
    			'historia' => 'Nuestros fundadores inician en el sector de entretenimiento para niños y jóvenes hace más de 30 años capitalizando a la fecha la experiencia en la fabricación e instalación de juegos y atracciones.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$400,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '$30,000.00',
    			'publicidad' => '$7,500.00',
    			'publicidad_institucional' => '$7,500.00',
    			'capital_trabajo' => '',
    			'inversion' => 'Urban: $6,400,000.00',
    			'retorno_inversion' => '45 meses',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '10 años',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '10',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'FISIOTERAPIA INTEGRAL CENTER',
    			'resumen' => 'Manejamos un modelo terapéutico integral; el cual nos permite atender todo tipo de lesiones. Nuestro principal objetivo es el movimiento. Buscamos una atención temprana, contamos con múltiples y diversos tratamientos los cuales nos permiten atender lesiones y patologías desde los primeros días de lesión hasta varios meses de haberse instaurado. Nuestros especialistas guían al paciente durante todo el período de rehabilitación. Disminuir el dolor y mejorar la movilidad son nuestros objetivos en cada uno de nuestros tratamientos los cuales se logran desde las primeras sesiones. Nuestro modelo terapeútico es único, permitiéndonos ver a la persona y la lesión desde un modelo funcional y biomecánico dirigido a reestablecer o mejorar el equilibrio corporal y así evitar o reincidir nuevamente en las lesiones. No solo nos preocupamos en atender, sino también en capacitar e instruir al paciente en todo su proceso de rehabilitación.',
    			'logo' => 'fisioterapia_integral.jpg',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$390,000 MXP',
    			'adaptacion_local' => '',
    			'regalias' => '',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$2´000,000 MXP',
    			'retorno_inversion' => '18 A 24 MESES',
    			'punto_equilibrio' => '6 A 9 MESES',
    			'utilidad' => '',
                'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '13',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'CARTOON ANIMACIONES',
    			'resumen' => 'Empresa 100% mexicana. Marca ampliamente reconocida, líderes en el mercado, contando además del salón de fiestas, con el mejor show con personajes de caricatura de todo México, lo que nos da una gran ventaja competitiva.',
    			'logo' => 'cartoon_animaciones.png',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$250,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '$5,600.00 (cuota fija)',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$976,320.00',
    			'retorno_inversion' => '19 meses (aprox)',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2003',
    			'procedencia' => 'Chihuahua, Chih',
    			'id_categoria' => '8',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'ACETONA PURA',
    			'resumen' => 'Estructura arquitectónica y diseño apegado a la comodidad del cliente, vista panorámica, piso abierto con espacios claramente delim­itados evitando muro divisorio el cual crearía instantáneamente un ambiente menos cálido y de integración nivel medio. Servicio de bebidas de bienvenida y atención personalizada desde tu primer llamada, con­trol intacto de agenda y visitas. Las instalaciones están equipadas con siste­ma envolvente de audio, reproducción de tus películas y series favoritas con visibilidad total de cualquier parte del salón. Contamos con iluminación cálida y luz natural indirecta.',
    			'logo' => 'acetona_pura.jpg',
    			'nosotros' => 'Un espacio dedicado a ti, a darte el gusto y con­sentirte para un disfrute total de nuestras instala­ciones superando tus expectativas con un servicio y ambiente incomparables que te envuelven cre­ando un estado de relajación y desconecte total de tu día a día, un mani-pedi salón conceptual que rompe esquemas. Nos reinventamos constantemente cuidando tu bienestar desarrollando nuestra propia línea de productos para el cuidado mani-pedi orgánicos preparados al momento con calidad GOLD libres de alcohol, parabenos y explotando las propie­dades mas puras de la naturaleza.',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$500,000.00',
    			'retorno_inversion' => '',
    			'utilidad' => 'Ventas semanales promedio: $72,000.00',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2016',
    			'procedencia' => 'Chihuahua, Chihuahua',
    			'id_categoria' => '3',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'DAC DR. AUTO & CASA',
    			'resumen' => 'Es una empresa privada de servicios profesionales para mantenimiento, reparación, remodelación, instalación y servicios de INMUEBLES & AUTOS.',
    			'logo' => 'dac_dr.jpg',
    			'nosotros' => '',
    			'historia' => 'Tiene su comienzo en la Cd. de Aguascalientes en el año 2008, convirtiéndose en Franquicia en el 2010.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$80,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '0% los primeros 8 años, posterior a ese tiempo $500.00 mensuales',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$150,000.00',
    			'retorno_inversion' => '',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2008',
    			'procedencia' => 'Aguascalientes, Aguascalientes',
    			'id_categoria' => '13',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'LA CABAÑA SMOKE HOUSE',
    			'resumen' => 'Cocina BBQ los platillos y salsas son de nuestra propia creación, y están acompañados de una atmósfera campirana al estilo del sur de USA.',
    			'logo' => 'smoke_house.png',
    			'nosotros' => '',
    			'historia' => 'Empresa 100% Chihuahuense del ramo restaurantero, fundada en 2009; Nuestra cocina es BBQ, Low and Slow, lo que significa que cocinamos a bajas temperaturas por largos periodos de tiempo.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '5%',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$6,000,000.00 a $8,000,000.00',
    			'retorno_inversion' => '3 años',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2009',
    			'procedencia' => 'Chihuahua, Chihuahua',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'FELIZ VIAJE',
    			'resumen' => 'Agencia de viajes',
    			'logo' => 'feliz_viaje.png',
    			'nosotros' => '',
    			'historia' => 'Corporativo con 8 años de experiencia en la Creación y Asesoría de viajes a todo el territorio nacional y extranjero. Actualmente tenemos 18 franquicias en el territorio nacional y 1 en el extranjero, iniciando nuestra oferta de franquicias en noviembre de 2016.',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$75,000.00',
    			'retorno_inversion' => 'De 8 a 12 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2009',
    			'procedencia' => 'Sonora',
    			'id_categoria' => '1',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Nápoles BarbersShop And Spa',
    			'resumen' => 'Empresa que brinda gran diversidad de productos de alta calidad y asesoría de imagen para caballeros.',
    			'logo' => 'napoles_barber_shop.png',
    			'nosotros' => '',
    			'historia' => 'Originarios de Nuevo León, y en tan solo 18 meses se tuvo un retorno de inversión',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$660,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '0%',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '',
    			'retorno_inversion' => '18 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => 'Nuevo León',
    			'id_categoria' => '2',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'The Barbers Spa',
    			'resumen' => 'Spa exclusivo para hombre, que ofrece un servicio profesional, para mantener, fomentar y mejorar la imagen en todos los aspectos. Cuentan con varios servicios con productos a aparatos diseñados únicamente para varones',
    			'logo' => 'barber_spa.png',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$180,000.00 más iva',
    			'adaptacion_local' => '',
    			'regalias' => '$3,500.00 FIJA, *Es un traspaso',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$1,500,000.00',
    			'retorno_inversion' => '24 - 36 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => '',
    			'id_categoria' => '2',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'More Shots',
    			'resumen' => 'Cócteles en shots, servicio de barras móviles de barras móviles de cócteles en shots para eventos en el país, son los precursores de las barras móviles para eventos.',
    			'logo' => 'more_shots.png',
    			'nosotros' => '',
    			'historia' => 'Originarios de Guadalajara, Jalisco',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => 'MORE SHOTS PLUS $350.000.00, MORE SHOTS $245.000.00',
    			'adaptacion_local' => '',
    			'regalias' => '$1,500.00 3er MES, $2,000.00 4to MES, EN ADELANTE $2,500.00',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '',
    			'retorno_inversion' => '',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2010',
    			'procedencia' => 'Guadalajara, Jalisco',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Thrifty',
    			'resumen' => 'Nieves de la más alta calidad. Cuenta con una amplia gama de sabores a elegir',
    			'logo' => 'thrifty.jpg',
    			'nosotros' => '',
    			'historia' => 'En los Estados Unidos, la marca Thrifty cuenta con 73 años de experiencia y llega a México a principios de los 90’s, consolidándose rápidamente como una de las marcas preferidas de los consumidores, gracias a la excelente calidad de los productos, elaborados con ingredientes seleccionados, mediante procesos de producción estrictamente apegados a los más altos estándares de calidad',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 345,000',
    			'adaptacion_local' => '',
    			'regalias' => '$ 10,000',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '',
    			'retorno_inversion' => '10-24 meses',
    			'utilidad' => '$ 50,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '1940',
    			'procedencia' => 'Estados Unidos',
    			'id_categoria' => '7',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Taco Baja',
    			'resumen' => 'Es la combinación del ambiente playero y el ambiente surf, con excelencia en sabor y calidad en productos del mar, así como la más amable atención al cliente. Estos productos son derivados de la cocina del estado de Baja California',
    			'logo' => 'taco_baja.jpg',
    			'nosotros' => '',
    			'historia' => 'Nace el 26 de abril de 2007 en una pequeña cabaña ubicada en la ciudad de Chihuahua, con el objetivo de ofrecer al público consumidor los famosos tacos de camarón y pescado, originarios de Ensenada, Baja California',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 250,000',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 800,000',
    			'retorno_inversion' => '14-18 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2007',
    			'procedencia' => 'Chihuahua, Chihuahua',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Visa Del Norte',
    			'resumen' => 'Boutique de productos cárnicos de la más alta calidad, especializada en cortes finos de bovino y alimentos preparados',
    			'logo' => 'visa_del_norte.jpg',
    			'nosotros' => '',
    			'historia' => 'Empresa surgida en la ciudad de Chihuahua en 1981 como un pequeño negocio de “Expendio de carne” y tienda de abarrotes. En 1986 se realizó una gran inversión en infraestructura y equipo, con la finalidad de procesar productos cárnicos de alta calidad',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 220,400',
    			'adaptacion_local' => '',
    			'regalias' => '1% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 1,589,600',
    			'retorno_inversion' => '19-21 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '1981',
    			'procedencia' => 'Chihuahua, Chihuahua',
    			'id_categoria' => '5',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Quiznos',
    			'resumen' => 'Quiznos sub es una marca reconocida a nivel global por sus famosas recetas de sandwiches estilo subs. Actualmente se diversifica de otros restaurantes de comida rápida por alta calidad de sus productos a precios sumamente accesibles. Sus recetas se conforman de una selección de productos frescos, carne, quesos y embutidos de primera calidad, cortados y preparados al momento en su gama de panes artesanales, para así generar una experiencia deliciosa para todo tipo de consumidores',
    			'logo' => 'quiznos_sub.jpg',
    			'nosotros' => '',
    			'historia' => 'Quiznos es una de las principales cadenas de restaurantes de “Quick service” a nivel global así como pionero en el concepto de sándwiches tostados desde 1981, abriendo sus puertas por primera vez en denver, colorado. En junio de 2013 la marca llega a México y hoy, con menos de dos años de la primera apertura, cuenta ya con 20 puntos de venta establecidos en distintos estados de la república mexicana. En 2015 está proyectado contar con 20 puntos de venta adicionales, representando así una marca con alta presencia y posicionamiento en el país',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '7% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 1,700,000',
    			'retorno_inversion' => '18-36 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2013',
    			'procedencia' => 'Estados Unidos',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Tortas Parra',
    			'resumen' => 'Restaurante especializado en tortas y tostadas hechas de carne de puerco y pollo',
    			'logo' => 'http://marcasyfranquicias.org/wp-content/uploads/2017/11/proyecto-13.jpg',
    			'nosotros' => '',
    			'historia' => 'Pioneros en el giro de tortas y tostadas con una trayectoria de 35 años de tradición, empezando con un pequeño local y un menú enfocado únicamente en tortas, y hoy en día especialistas en tema de tortas y tostadas de gran variedad y sabores de carne de puerco y pollo',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 270,000',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 1,630,000 (con cuota inicial)',
    			'retorno_inversion' => '20 meses',
    			'utilidad' => '',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '1982',
    			'procedencia' => 'Nuevo Casas Grandes, Chihuahua',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Misión Salud',
    			'resumen' => 'Es un concepto de negocio bajo el formato de revista de publicación mensual, compuesta en la parte editorial por artículos médicos y de especialistas en diferentes temas de salud, y por la parte comercial por diferentes industrias en la rama de salud, educación, financiera, hotelera, etc',
    			'logo' => 'mision_salud.jpg',
    			'nosotros' => '',
    			'historia' => 'Empresa dedicada a la publicación periódica de revistas del sector salud por más de 20 años. Actualmente opera en México (Monterrey, Chihuahua, Mérida, Guadalajara, Morelia, Torreón y Ciudad de México) y Bolivia (Santa Cruz, Cochabamba, La Paz)',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$360,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$540,000.00',
    			'retorno_inversion' => '13 meses',
    			'utilidad' => '$30,000.00 - $40,000',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '1997',
    			'procedencia' => 'Monterrey, Nuevo León',
    			'id_categoria' => '12',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Spin Hiit',
    			'resumen' => 'Sistema de acondicionamiento físico es una forma mejorada de entrenamiento, es una estrategía de ejercicios que alterna periodos de ejercicio anaeróbico y aeróbico intenso corto, con periodos menos intensos de recuperación. El entrenamiento metabólico es una forma de ejercicio cardiovascular y de tonificación muscular',
    			'logo' => 'spin_hit.png',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 800,000',
    			'retorno_inversion' => '18-24 meses',
    			'utilidad' => '$ 40,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2015',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '6',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'La Reina De Sonora',
    			'resumen' => 'Franquicia de distribución dedicado a la venta de productos regionales de sonora. Los franquiciantes son los productores de la carne seca, machaca, coyotas, dulces regionales, etc',
    			'logo' => 'reina_sonora.jpg',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 215,000',
    			'adaptacion_local' => '',
    			'regalias' => '',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '',
    			'retorno_inversion' => '12 meses',
    			'utilidad' => '	$ 25,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '1987',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '5',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Cananea Buffalo’s Steak & Wings',
    			'resumen' => 'Restaurante especializado en cortes de carne y alitas. Cuentan con servicio a la mesa, servicio para llevar, reservaciones para eventos especiales, salas privadas y música en vivo',
    			'logo' => 'cannanea_bufalos.jpg',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 250,000',
    			'adaptacion_local' => '',
    			'regalias' => '4% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 2,300,000 (con cuota inicial)',
    			'retorno_inversion' => '30-39 meses',
    			'utilidad' => '$ 400,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'KEGS Barriles Y Equipos Draught',
    			'resumen' => 'Empresa dedicada a la venta de cerveza de barril a domicilio con la opción de equipos con sistema draught',
    			'logo' => 'kegs.jpg',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 180,000',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 900,000 (con cuota inicial)',
    			'retorno_inversion' => '18-14 meses',
    			'utilidad' => '$ 35,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2009',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '5',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Cynthia Mujer Y Moda',
    			'resumen' => 'Empresa vanguardista dedicada a la comercialización de ropa femenina. Cuentan con una amplia gama de artículos de moda',
    			'logo' => 'cynthia.jpg',
    			'nosotros' => '',
    			'historia' => 'Franquicia Cynthia mujer & moda, es una empresa mexicana fundada en 1984 en la ciudad de Hermosillo, Sonora. La empresa es representada por Cynthia Mariscal Monge',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 200,000',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 750,000 (con cuota inicial)',
    			'retorno_inversion' => '24-36 meses',
    			'utilidad' => '$ 30,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '1984',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '4',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Eventos Elite',
    			'resumen' => 'Es una empresa dinámica y profesional, con varios años de experiencia en el sector de la realización de eventos',
    			'logo' => 'eventos_elite.png',
    			'nosotros' => '',
    			'historia' => '',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 150,000',
    			'adaptacion_local' => '',
    			'regalias' => '$ 5,000',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 780,000 (con cuota inicial)',
    			'retorno_inversion' => '24-36 meses',
    			'utilidad' => 'Variable',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2008',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '8',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Tu Rollo Cinco',
    			'resumen' => 'Restaurante de comida oriental con ambiente familiar, la cual es una empresa socialmente responsable, apoyando a diferentes organizaciones sociales. Cuenta con platillos personalizados por los clientes, una variedad de 20 ingredientes a elegir y cinco diferentes tipos de salsas para alitas y boneless',
    			'logo' => 'tu_rollo_cinco.jpg',
    			'nosotros' => '',
    			'historia' => 'Es un restaurante de comida oriental con 10 años en el mercado. Actualmente cuenta con 6 sucursales, los cuales son los más exitosos de hermosillo, sonora',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 200,000',
    			'adaptacion_local' => '',
    			'regalias' => '$ 10,000',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 250,000',
    			'retorno_inversion' => '12-18 meses',
    			'utilidad' => '$ 25,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2007',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Green Garden Salads',
    			'resumen' => 'Es una empresa dedicada a la preparación de comida saludable, con un amplio menú frío y caliente, además de recetas exclusivas de aderezos, todo en un ambiente de confort y armonía',
    			'logo' => 'green_garden.jpg',
    			'nosotros' => '',
    			'historia' => 'Nace en Hermosillo, Sonora al ver la necesidad de un lugar de comida saludable con precios accesibles y variedad en los productos',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 180,000',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 255,000',
    			'retorno_inversion' => '12-24 meses',
    			'utilidad' => '$ 35,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Elsa Glorias',
    			'resumen' => 'Esta empresa rompe con el esquema tradicional de punto de venta de pasteles, logrando un concepto agradable, en donde se transmite la experiencia de estar en el calor del hogar',
    			'logo' => 'elsa_gloria.jpg',
    			'nosotros' => '',
    			'historia' => 'Nace en Hermosillo, Sonora en casa de la familia León Fonseca por el gusto de la repostería fina de la señora Elsa Gloria, hoy en día, en cada unidad, se crea la experiencia de los inicios de la pastelería al ir por un postre a casa de los leon fonseca',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$ 250,000',
    			'adaptacion_local' => '',
    			'regalias' => '5% sobre ventas netas',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 250,000',
    			'retorno_inversion' => '18-24 meses',
    			'utilidad' => '$ 40,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '9',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'Barbaroja Barbería & Spa',
    			'resumen' => 'Barbería y spa exclusivo para caballeros',
    			'logo' => 'barba_roja.jpg',
    			'nosotros' => '',
    			'historia' => 'Nace en la ciudad de Hermosillo, Sonora, con el fin de ofrecer una nueva alternativa de barbería tradicional unificada con spa y ofrecer venta de producto para el cuidado personal masculino, con el mejor ambiente de las tradicionales barberías antiguas',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '$125,000.00',
    			'adaptacion_local' => '',
    			'regalias' => '$ 3,500',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$255,000.00',
    			'retorno_inversion' => '12-18 meses',
    			'utilidad' => '$ 35,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2016',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '2',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],

    		[
    			'franquicia' => 'La Carreta Verde',
    			'resumen' => 'Elaboración y venta de sandwichs, jugos naturales, smoothies, licuados naturales',
    			'logo' => 'carreta_verde.png',
    			'nosotros' => '',
    			'historia' => 'Se crea al ver la necesidad de un establecimiento de comida sana, de “pasadita”, higiénico y precios competitivos',
    			'mision' => '',
    			'vision' => '',
    			'cuota_inicial' => '',
    			'adaptacion_local' => '',
    			'regalias' => '$ 3,500',
    			'publicidad' => '',
    			'publicidad_institucional' => '',
    			'capital_trabajo' => '',
    			'inversion' => '$ 270,000',
    			'retorno_inversion' => '12 meses',
    			'utilidad' => '$ 20,000 (promedio mensual)',
    			'punto_equilibrio' => '',
    			'contrato' => '',
    			'inicio_operaciones' => '2015',
    			'procedencia' => 'Hermosillo, Sonora',
    			'id_categoria' => '11',
    			'created_at' => new DateTime,
    			'updated_at' => new DateTime
    		],
    	);

        Franquicias::insert($data);
    }
}
